# Conditional build stages
# - Run Deployment only on master when code is pushed
stages:
    - name: Python Tests
    - name: UI Tests
    - name: Deployment
      if: branch = master AND type = push


# Following stages will run sequentially
jobs:
    include:
        - stage: Python Tests
          language: python
          python: 3.7
          install: pip install -r requirments/development.txt
          script: make test-data

        - stage: UI Tests
          language: node_js
          node: 12
          install: yarn install --production=false
          script: make test-frontend

        - stage: Deployment
          language: node_js
          node_js: 12
          install: yarn install --production=false
          script: make build-frontend
          deploy:
            provider: pages
            skip_cleanup: true
            github_token: $GITHUB_TOKEN
            keep_history: true
            cleanup: false
            local_dir: dist
            on:
                branch: master
