
# the following line is needed to enable the TravisCI build conditions
conditions: v1

# Conditional build stages
stages:
    - name: Python Tests
    - name: UI Tests
    - name: Deployment
      if: branch = master


# Following stages will run sequentially
jobs:
    include:

        - stage: Python Tests
          language: python
          python: 3.7
          install: pip install -r requirments/development.txt
          script: make test-data

        - stage: UI Tests
          language: node_js
          node: 12
          install: yarn install --production=false
          script: make test-frontend

        - stage: Deployment
          - language: python
            python: 3.7
            install: pip install -r requirments/development.txt
            script: make build-data
          - language: node_js
            node_js: 12
            install: yarn install --production=false
            script: make build-frontend


# Github pages development
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist
    on:
        branch: master
