language: python

python:
    - "3.7"

before-deploy:
    - make build-all

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist
    on:
        branch: master
jobs:
    include:
        - language: python
          python: 3.7
          install:
              - pip install -r requirments/development.txt
          script:
              - make test-data

        - language: node_js
          nodejs: 12
          install:
              - yarn install --production=false
          script:
              - make test-frontend



