language: python

python:
    - "3.7"

install:
    - pip install -r requirments/development.txt

script:
    - make test

before-deploy:
    - make build-all

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist
    on:
        branch: master
